SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `state`;
DROP TABLE IF EXISTS `country`;
DROP TABLE IF EXISTS `institution_admin`;
DROP TABLE IF EXISTS `institution`;
DROP TABLE IF EXISTS `program_category`;
DROP TABLE IF EXISTS `institution_contact`;
DROP TABLE IF EXISTS `institutional_program`;
DROP TABLE IF EXISTS `goal`;
DROP TABLE IF EXISTS `parent_consent`;
DROP TABLE IF EXISTS `institution_affiliation_code`;
DROP TABLE IF EXISTS `mentee`;
DROP TABLE IF EXISTS `mentor`;
DROP TABLE IF EXISTS `mentee_feedback`;
DROP TABLE IF EXISTS `mentor_feedback`;
DROP TABLE IF EXISTS `mentee_mentor_program`;
DROP TABLE IF EXISTS `mentee_mentor_goal`;
DROP TABLE IF EXISTS `task`;
DROP TABLE IF EXISTS `mentee_mentor_task`;
DROP TABLE IF EXISTS `professional_experience_data`;
DROP TABLE IF EXISTS `event`;
DROP TABLE IF EXISTS `activity`;
DROP TABLE IF EXISTS `institution_agreement`;
DROP TABLE IF EXISTS `user_role`;
DROP TABLE IF EXISTS `institution_agreement_user_role`;
DROP TABLE IF EXISTS `user_user_role`;
DROP TABLE IF EXISTS `personal_interest`;
DROP TABLE IF EXISTS `weighted_personal_interest`;
DROP TABLE IF EXISTS `professional_interest`;
DROP TABLE IF EXISTS `weighted_professional_interest`;
DROP TABLE IF EXISTS `document_category`;
DROP TABLE IF EXISTS `document`;
DROP TABLE IF EXISTS `useful_link`;
DROP TABLE IF EXISTS `responsibility`;
DROP TABLE IF EXISTS `program_useful_link`;
DROP TABLE IF EXISTS `program_document`;
DROP TABLE IF EXISTS `goal_useful_link`;
DROP TABLE IF EXISTS `task_useful_link`;
DROP TABLE IF EXISTS `goal_document`;
DROP TABLE IF EXISTS `task_document`;
DROP TABLE IF EXISTS `custom_assigned_goal_data`;
DROP TABLE IF EXISTS `custom_assigned_task_data`;
DROP TABLE IF EXISTS `forgot_password`;
DROP TABLE IF EXISTS `institution_admin_access_request`;
DROP TABLE IF EXISTS `professional_consultant_area`;
DROP TABLE IF EXISTS `goal_category`;
DROP TABLE IF EXISTS `event_invited_mentor`;
DROP TABLE IF EXISTS `event_invited_mentee`;
DROP TABLE IF EXISTS `institutional_program_document`;
DROP TABLE IF EXISTS `institutional_program_link`;
DROP TABLE IF EXISTS `mentor_professional_area`;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;